### ISSUE TITLE
TimeSpanPicker not included in build

### ISSUE THREAD

**Issue by dasjestyr** [Coding4FunProjects/Coding4FunToolkit#4]
TimeSpanPicker isn't available through any of the compiled assemblies. I noticed the folder that has this control doesn't even have an associated project. I tried pulling it in myself, but it wont build because it would seem that all of the dependent classes have been altered. Is this control discontinued?

**Comment by hermitdave** [comment]
Hey,
I had issues getting this control to work on WinRT api. I will have a look again when I am doing Windows 10 port

Hermit
