### ISSUE TITLE
ColorPicker throws exception at designer preview

### ISSUE THREAD

**Issue by vincegio** [Coding4FunProjects/Coding4FunToolkit#5]
Hi, 
upon adding a colorPicker control to the design preview, it throws an error (after restarting VS and opening the designer again), something about sizeChanged.

People tell me that it has to do that the event is trying to be called when the project is in designview.

**Comment by hermitdave** [comment]
What version of visual studio are you using? Does this happen with phone version or windows 8x projects?

Sent from my Lumia 1520

**Comment by vincegio** [comment]
Hi, thank you for replying :)

I am using VS 2013 Update 4 with Windows 8.1 RT environment.
[Image](http://puu.sh/i8Q4o/8a8c28524a.png)

With the error `Object reference not set to an instance of an object.`

The error disappears after commenting out the code

``` XAML
<Controls:ColorPicker x:Name="fgPicker" ColorChanged="fgPicker_ColorChanged" />
```

Had a dialog with a guy from MS who said that it's most likely due to the fact that it's calling for an event to be raised in designpreview as it works without a flaw on my phone when debugging. I can even run it when the error is raised, hence it must be something over at VS.

Keep me updated :)

**Comment by hermitdave** [comment]
Let me try and replicate this today. I might push it out as a change alongside windows 10 support

Sent from my Lumia 1520

**Comment by vincegio** [comment]
Thanks!
If you need any more info or similar, don't hesitate to write here.

Sent from my Lumia 930

---

Från: hermitdavemailto:notifications@github.com
Skickat: ‎2015-‎06-‎02 06:32
Till: Coding4FunProjects/Coding4FunToolkitmailto:Coding4FunToolkit@noreply.github.com
Kopia: Vincent Giorgimailto:mrvince@hotmail.se
Ämne: Re: [Coding4FunToolkit] ColorPicker throws exception at designer preview (#5)

Let me try and replicate this today. I might push it out as a change alongside windows 10 support

Sent from my Lumia 1520

**Comment by vincegio** [comment]
Hi, how's the progress?

**Comment by hermitdave** [comment]
Thanks for checking on me.. I just reverted to subdue 8.1 and vs 2013.. Let me have a look now

Sent from my Lumia 1520

**Comment by vincegio** [comment]
Thanks! :)

Date: Mon, 8 Jun 2015 14:26:18 -0700

**Comment by hermitdave** [comment]
It's been a while since I uploaded anything. Let me deploy a beta package to test the tweak. Erik let you know how it goes

Sent from my Lumia 1520

**Comment by vincegio** [comment]
Alright, great!

**Comment by hermitdave** [comment]
No luck so far.. not much in stack trace and no poblems when project is attached. This except primarily arises from nuget reference. All I can do right now is catch the exception but that results in a big block blob as opposed to rendered control.

I suppose that is better than design time error.

Date: Tue, 9 Jun 2015 01:13:00 -0700

**Comment by vincegio** [comment]
Ah you mean that it'll just be "invisible"?
I personally have no issue with that, it's easy to debug it on a device or emulator to get a visualization of it :)

**Comment by hermitdave** [comment]
Agreed though its a pain.. let me keep an eye on it.. maybe I will spot the problem bit

Date: Tue, 9 Jun 2015 04:54:00 -0700

**Comment by vincegio** [comment]
Perfect, keep me updated!

**Comment by vincegio** [comment]
Hi, how is the progress on this? Really curious, I tried the beta out and the control is still throwing an exception.
