### ISSUE TITLE
Need ToastPrompt for UWP.

### ISSUE THREAD

**Issue by bc3tech** [Coding4FunProjects/Coding4FunToolkit#6]
Since Windows and Windows Phone can do toasts, would be great to have ToastPrompt on both. Realize that on Desktop/Tablet the toast may be a _little_ different (not OS-level appearance) but could fly in from the bottom right of the app frame w/ the appropriate style to be acceptable.

**Comment by hermitdave** [comment]
I have added ToastPrompt to Windows version of toolkit.. closing the issue now
