### ISSUE TITLE
Setting SuperImage.Source to null does not remove the image

### ISSUE THREAD

**Issue by JulleR** [Coding4FunProjects/Coding4FunToolkit#7]
I encountered a problem with SuperImage in virtualized lists where some list items set null as SuperImage.Source, but they still got an image. Naturally, the reason was that the list recycled the items so those nulled SuperImage's kept their original images. It would be nice if nulling the source would remove the image.

**Comment by hermitdave** [comment]
I encountered similar issue with another control a while back. Let me see try and tweak the behaviour.

**Comment by hermitdave** [comment]
I have pushed 2.1.4. Can you please update and test ? I am assuming setting Source property for SuperImage.

**Comment by JulleR** [comment]
Wow, that was fast. Thanks! Now the image is cleared correctly, but in my case I'd like it to show the placeholder image even when Source is null, but it's not shown. I'm not sure what the best solution would be here since probably not everyone wants the placeholder when Source=null. Maybe there could be a property for forcing the placeholder in such scenarios. Anyway, this fixed the issue I reported.

**Comment by hermitdave** [comment]
I have published a tweak to the control 2.1.5.. have a go. I myself need to check the placeholder behaviour in another control I created recently. If this doesn't work, I will try to find a way around

**Comment by JulleR** [comment]
Thanks, it works!
