### ISSUE TITLE
XamlParseException when using in WP8 project

### ISSUE THREAD

**Issue by ScottIsAFool** [Coding4FunProjects/Coding4FunToolkit#8]
From email sent to nuget package owners: 

Hi! Just to report that the RoundButton control raises the following exception with version 2.1.5 (wp8 assemblies):

A first chance exception of type 'System.Windows.Markup.XamlParseException' occurred in System.Windows.ni.dll

Additional information: Failed to create a 'System.Type' from the text 'local:RectangularButton'. [Line: 146 Position: 21]

**Comment by ScottIsAFool** [comment]
By the looks of it, RectangularButton is missing from the csproj (https://github.com/Coding4FunProjects/Coding4FunToolkit/blob/master/source/Coding4Fun.Toolkit.Controls.WindowsPhone8/Coding4Fun.Toolkit.Controls%20(WP8).csproj)

**Comment by hermitdave** [comment]
my mistake.. incorrectly named xaml file meant that WP8 / SL8 generic xaml had reference to Rectangular Button control. I have added that control to SL as it was easier that way and released an udpate
